### PR TITLE
Re-number gcc 7.2.0 patches

### PR DESCRIPTION
**Pull request by michaelforney**
I went to rebase the 7.2.0 patches on 7.3.0 by first applying on `gcc-7_2_0-release`, but they didn't apply cleanly with a plain `git apply`. So I went back to the 6.3.0 patches and rebased on 7.2.0. I think I found a couple of mistakes in the 7.2.0 patch set for the j2 patch, so I fixed those in the process.

I then rebased on `gcc-7_3_0-release`. The static pie patch had some conflicts due to https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=81523, but I believe I have resolved them correctly.

It would be nice to have these patch sets formatted with `git format-patch` so they can easily be applied, rebased, and regenerated. Do you have author information we could use for the commits?

### CODE REVIEW

**Comment by rofl0r** [comment]
yesterday in `#musl`:
```
<nsz> [18:00:39] mcm patches for gcc-7.3.0 + binutils-2.28.1: http://port70.net/~nsz/musl/mcm73/
<nsz> [18:02:02] still testing, but at least the toolchain builds for all targets i tried so far
```

**Comment by michaelforney** [comment]
Ah, great! Let me compare the patch sets.

Looks like it drops the static PIE patch. Not sure if this was intentional or not. gcc-7.3.0 make it so `-static` overrides `-pie`.

I also noticed that it contains the same typo (I think) as the gcc-7.2.0:

```diff
-		sh[1234]*be-*-* | sh[1234]*eb-*-*) with_endian=big ;;
+		sh[j1234]*be-*-* | sh[n1234]*eb-*-*) with_endian=big ;;
```

whereas the gcc-6.3.0 patch contains

```diff
-               sh[1234]*be-*-* | sh[1234]*eb-*-*) with_endian=big ;;
+               sh[j1234]*be-*-* | sh[j1234]*eb-*-*) with_endian=big ;;
```

Can anyone confirm whether this `n1234` is correct or just a typo?

**Comment by rofl0r** [comment]
has this PR been updated in regard to the answers given by nsz in IRC ?

**Comment by michaelforney** [comment]
Not sure exactly which updates you are referring to, but looking at nsz's newest patches (http://port70.net/~nsz/musl/mcm73/0003-add-gcc-7.3.0-patches.patch), I see that he fixed the j2 typo and re-added the static PIE patch. All other patches are identical.

Comparing the static PIE patches, nsz's patch seems to be attempting to handle the gcc-8 `-static-pie` option. I don't understand this since `-static-pie` is an invalid option for gcc-7 (even after applying nsz's patches):
```
x86_64-linux-musl-gcc: error: unrecognized command line option ‘-static-pie’; did you mean ‘-static’?
```

Apart from that, I see that nsz's patch is missing the hunk
```diff
@@ -101,8 +99,7 @@ see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
   "%{fvtable-verify=none:%s; \
      fvtable-verify=preinit:vtv_end_preinit.o%s; \
      fvtable-verify=std:vtv_end.o%s} \
-   %{static:crtend.o%s; \
-     shared|pie:crtendS.o%s; \
+   %{shared|pie:crtendS.o%s; \
      :crtend.o%s} \
    crtn.o%s \
    " CRTOFFLOADEND
```

I'm not sure how important this is since it is in the `!HAVE_LD_PIE` section, though it does still mention `shared|pie`...

nsz's patch also has these two hunks
```diff
@@ -132,12 +131,14 @@ see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
 #define LIB_SPEC GNU_USER_TARGET_LIB_SPEC

 #if defined(HAVE_LD_EH_FRAME_HDR)
-#define LINK_EH_SPEC "%{!static:--eh-frame-hdr} "
+#define LINK_EH_SPEC "%{!static|" PIE_SPEC ":--eh-frame-hdr} "
 #endif
```
```diff
diff --git a/gcc/config/rs6000/sysv4.h b/gcc/config/rs6000/sysv4.h
index cbee89140dd..6aaef5a4d2a 100644
--- a/gcc/config/rs6000/sysv4.h
+++ b/gcc/config/rs6000/sysv4.h
@@ -762,12 +762,12 @@ ENDIAN_SELECT(" -mbig", " -mlittle", DEFAULT_ASM_ENDIAN)
 #define        STARTFILE_LINUX_SPEC \
   "%{shared:; \
      pg|p|profile:gcrt1.o%s; \
-     static:crt1.o%s; \
+     static|static-pie:%{" PIE_SPEC ":rcrt1.o%s;:crt1.o%s}; \
      " PIE_SPEC ":Scrt1.o%s; \
      :crt1.o%s} \
    %{mnewlib:ecrti.o%s;:crti.o%s} \
-   %{static:crtbeginT.o%s; \
-     shared|" PIE_SPEC ":crtbeginS.o%s; \
+   %{shared|" PIE_SPEC ":crtbeginS.o%s; \
+     static:crtbeginT.o%s; \
      :crtbegin.o%s} \
    %{fvtable-verify=none:%s; \
      fvtable-verify=preinit:vtv_start_preinit.o%s; \
@@ -780,8 +780,7 @@ ENDIAN_SELECT(" -mbig", " -mlittle", DEFAULT_ASM_ENDIAN)
   "%{fvtable-verify=none:%s; \
      fvtable-verify=preinit:vtv_end_preinit.o%s; \
      fvtable-verify=std:vtv_end.o%s} \
-   %{static:crtend.o%s; \
-     shared|" PIE_SPEC ":crtendS.o%s; \
+   %{shared|" PIE_SPEC ":crtendS.o%s; \
      :crtend.o%s} \
    %{mnewlib:ecrtn.o%s;:crtn.o%s} \
    " CRTOFFLOADEND
```
These changes aren't present in any of the older patch sets. If we are going to add them to the 7.3.0 patch set, should we also backport them to the older ones?

**Comment by dtzWill** [comment]
Friendly ping!

**Comment by tmh1999** [comment]
I apply nsz updated patches (Feb 28) in http://port70.net/%7Ensz/musl/gcc-7.3.0/ into Alpine aports gcc 6.4.0 tree and compile on Alpine edge on x86_64 and s390x, and they work.

Compiling hello world with -static-pie also works.

Only ssp (0001) and s390x ldso (0010) patches are not needed as Alpine already had them. But they still make sense for musl-cross-make.

Even thought I have not applied/tested @michaelforney  patches, I think nsz patches above are good to be merged @richfelker .

**Comment by cHolzberger** [comment]
+1

**Comment by richfelker** [comment]
I think everything from this PR has been done now. Is that correct?

**Comment by michaelforney** [comment]
I still think it would be good to renumber the 7.2.0 patches and make sure they apply cleanly. I updated the PR to contain only the first commit.

The net effect is this diff:
```diff
diff --git a/gcc/config.gcc b/gcc/config.gcc
index 55b61b331e5..50906fd447f 100644
--- a/gcc/config.gcc
+++ b/gcc/config.gcc
@@ -2657,7 +2657,7 @@ sh-*-elf* | sh[12346lj]*-*-elf* | \
 	tmake_file="${tmake_file} sh/t-sh sh/t-elf"
 	if test x${with_endian} = x; then
 		case ${target} in
-		sh[j1234]*be-*-* | sh[n1234]*eb-*-*) with_endian=big ;;
+		sh[j1234]*be-*-* | sh[j1234]*eb-*-*) with_endian=big ;;
 		shbe-*-* | sheb-*-*)		   with_endian=big,little ;;
 		sh[1234]l* | sh[34]*-*-linux*)	   with_endian=little ;;
 		shl* | sh*-*-linux* | \
diff --git a/gcc/config/sh/sh-protos.h b/gcc/config/sh/sh-protos.h
index 52a08f02ac5..59be4c0cf30 100644
--- a/gcc/config/sh/sh-protos.h
+++ b/gcc/config/sh/sh-protos.h
@@ -35,9 +35,6 @@ enum sh_function_kind {
   SFUNC_STATIC
 };
 
-#define TARGET_ATOMIC_HARD_CAS \
-  (selected_atomic_model ().type == sh_atomic_model::hard_cas)
-
 #ifdef RTX_CODE
 extern rtx sh_fsca_sf2int (void);
 extern rtx sh_fsca_int2sf (void);
diff --git a/gcc/config/sh/sh.h b/gcc/config/sh/sh.h
index 8f483635747..9e24649d189 100644
--- a/gcc/config/sh/sh.h
+++ b/gcc/config/sh/sh.h
@@ -393,6 +393,9 @@ extern const sh_atomic_model& selected_atomic_model (void);
 #define TARGET_ATOMIC_SOFT_IMASK \
   (selected_atomic_model ().type == sh_atomic_model::soft_imask)
 
+#define TARGET_ATOMIC_HARD_CAS \
+  (selected_atomic_model ().type == sh_atomic_model::hard_cas)
+
 #endif // __cplusplus
 
 #define SUBTARGET_OVERRIDE_OPTIONS (void) 0
```

**Comment by michaelforney** [comment]
Well, this pull request has outlived my interest in gcc-7.2.0, but I think it would still be good to apply to fix the issues mentioned in https://github.com/richfelker/musl-cross-make/pull/40#issuecomment-463036466 and to make the patches apply cleanly.

**Comment by michaelforney** [comment]
Closing, gcc-7.2.0 support was removed in 49f489e5c6ece5ebaf6b01542f9672dcea99495b.

**Pull request closed without merging**
