### PR TITLE
add gcc 8.4 hash and patches

### PR DESCRIPTION
**Pull request by JakubVanek**
Hi,

this PR adds the GCC 8.4.0 hash and copies the patches from GCC 8.3.0. I have regenerated all patches by applying them to a Git clone of `releases/gcc-8.4.0` and then reexporting them via git diff. The only patch that I have removed is `0017-pr93402.diff`, which is now already present as per https://web.archive.org/web/20200309214347/https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93402

Best regards,

Jakub

### CODE REVIEW

**Comment by richfelker** [comment]
Is there a reason you regenerated them? If the originals apply, I'd like to keep them as-is so that it's clear to ppl reading the source (e.g. diffing the diffs) that nothing changed. Reading regenerated ones requires heavy manual review to ensure there weren't unwanted changes.

**Comment by JakubVanek** [comment]
Nope, the originals were still applying OK. I was comparing patches for GCC 8.3 and GCC 9.2 and found them to be different, so I thought that the patches are always reapplied. I have fixed this by now copying the old patches unchanged instead.

**Comment by rofl0r** [comment]
this can be closed as c4c5b49efa3ad5772e5fe890d5042c34d9f4bfcf was merged.

**Comment by JakubVanek** [comment]
Agreed, thank you!

**Pull request closed without merging**
