### PR TITLE
gcc 7.1.0 support

### PR DESCRIPTION
**Pull request by pattop**
This is a rebase & conflict resolution of the gcc 6.3.0 patches onto gcc 7.1.0.

Successfully builds the following targets:
x86_64-linux-musl
arm-linux-musleabi (with native host and HOST=x86_64-w64-mingw32)
sh2eb-linux-muslfdpic

Hope this is helpful,

Patrick

### CODE REVIEW

**Comment by xoac** [comment]
So it's look u resolve my issue #31. Thank you!

**Comment by pattop** [comment]
Hi xoac. I don't think this is related to #31. It looks to me like you were trying to build gcc 6.3.0 using gcc 7.1.0. This patch adds support for building gcc 7.1.0 with musl-cross-make.

**Comment by richfelker** [comment]
I'm finally merging these with the change from 7.1 to 7.2 squashed and without the makefile change making it default - generally I do that separately, and here I'd especially like to since I'm just now getting around to actually trying gcc7 and don't know if anything might be broken, Thanks! And sorry for taking so long to get to this.

**Comment by pattop** [comment]
No problem. I've used gcc7 extensively over the past few months on arm and x86_64 without issue. I don't use the sh2 target so there could be unresolved issues there.

**Pull request closed without merging**
