### PR TITLE
Build on Mac OS X El Capitan

### PR DESCRIPTION
**Pull request by cfriedt**
The build on Mac OS X El Capitan dies while building musl when attempting to create empty .a files using ar. This is due to Apple's ar program behaving slightly different than the typical GNU ar.

```
...
istd/writev.lo` obj/ldso/dlstart.lo obj/ldso/dynlink.lo -lgcc -lgcc_eh
rm -f lib/libm.a
ar rc lib/libm.a
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[1]: *** [lib/libm.a] Error 1
make: *** [musl/.mcm_built] Error 2
```

The error was obviously because there were "no archive members specified".

To create an empty static archive on a mac that does not break Apple's linker, all you need to do is create an empty .a file using touch.

### CODE REVIEW

**Comment by rofl0r** [comment]
the mac ar program does indeed gratuitously have different command line options.

**Comment by richfelker** [comment]
I don't think just adding an empty .o file is the right solution; it's possible that the OSX native toolchain's ar is producing archive files in a different format than what's needed for the target. Adding CROSS_COMPILE=$(TARGET)- to the musl configure command line would get musl to correctly use the ar for the target, I think, but I should fix things in musl and mcm so that this just happens correctly on its own with no explicit action.

**Comment by richfelker** [comment]
I realized the fix I'm looking at in musl itself is good but not sufficient for musl-cross-make since musl can't be expected to find the new ar/ranlib that aren't in the PATH. Can you try adding AR=$(OUTPUT)/bin/$(TARGET)-ar and RANLIB=$(OUTPUT)/bin/$(TARGET)-ranlib to the end of the musl make command line in the mcm Makefile's rule for the musl/.mcm_built target? If that works for you I'll commit such a change.

**Comment by richfelker** [comment]
FYI I just tested this on gccfarm and the correct AR was invoked, so I think it's fine. I'll probably commit it soon, then work on integrating the new toolchain build (which will require a slightly different approach).

**Comment by FiloSottile** [comment]
This seems to be solved.

**Pull request closed without merging**
