### PR TITLE
add support for GCC 6.5.0

### PR DESCRIPTION
**Pull request by rofl0r**
new patch: 0017-c++-abi-break.diff fixes a C++ ABI break regression.

0010-static-pie-support.diff was removed as it doesn't apply anymore,

waiting for somebody to forward port 0010-static-pie-support.diff

### CODE REVIEW

**Comment by richfelker** [comment]
This needs forward port of `0010-static-pie-support.diff` to move forward.

**Comment by rofl0r** [comment]
instead of forward-porting, i added the 2 patches reversing the changes, just like gcc-7.3.0 does.
should i squash the 2 commits together ?

**Comment by rofl0r** [comment]
ping

**Comment by richfelker** [comment]
Squashed and merged. Thanks!

**Pull request closed without merging**
